# Header
menu:
  Home: /
  About: /about
  Github:
    url: https://github.com/gmlwo530

# Title on top left of menu. Leave empty to use main blog title
menu_title: Maru's blog

# URL of the Home page image
index_cover:

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:

google_analytics:

favicon:

github_url: https://github.com/gmlwo530
mailto:
